function multihead = multihead_attention(queries, keys, values)
    attention1 = scaled_dp_attention(reshape(queries(1,:,:), size(queries,2), 32), ...
                 reshape(keys(1,:,:), size(keys,2), 32), reshape(values(1,:,:), ...
                 size(values,2), 32));
    attention2 = scaled_dp_attention(reshape(queries(2,:,:), size(queries,2), 32), ...
                 reshape(keys(2,:,:), size(keys,2), 32), reshape(values(2,:,:), ...
                 size(values,2), 32));
    multihead = [attention1 attention2];
end